//
//  AppRelatedVC.swift
//  TestingDemo
//
//  Created by Vedvyas Rauniyar on 21/11/19.
//  Copyright © 2019 Apple. All rights reserved.
//

import UIKit

class AppRelatedVC: UIViewController {

    @IBOutlet weak var appRelTableView: UITableView!
    var titleArray = [String]()
    var detailArray = [String]()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setUpView()
    }
    
    func setUpView() {
        titleArray = ["I am not receiving my OTP. What should I do?","Do I have to Register on the app to check my Credit Health?","Will I receive a call from Wishfin on using the Wishfin FinHealth App?"]
        detailArray = ["At times, there is trouble receiving OTPs due to various telecom related or technical issues. We would request you to try again. If that doesn’t work out, please connect with us at contactus@wishfin.com.My Credit-related statistics / score is not accurate.Wishfin does not directly provide you the credit health report and the statistics. We merely present the information generated by TransUnion Cibil based on the information they have. Wishfin does not take responsibility for the veracity of the same.While there different credit rating agencies on the market which might generate different score for the same profile. However, banks only consider Cibil data before giving you a loan - hence our Credit Health check is based on the same. In case of further questions about your Cibil Report, please contact the TransUnion Cibil helpline at +91 - 22 - 6140 4300","The first time you use the app, your mobile number is verified and authenticated, a Wishfin account is auto-created for you for present and future use. This is important for security and accuracy. This enables us to authenticate you keep your Credit information just for your eyes. Every time you open the app, you will be requested to Login using Mobile OTP verification, to prevent any unauthorized access. Based on this account, you are entitled to your 12 Month CIBIL Membership.However, if for any reason, you wish to delete your Wishfin account and records, we respect that. Just drop us a line on contactus@wishfin.com and we’ll do the needful. Please note that this will not affect your Cibil data that resides with TransUnion and Banks, as this is, in no way, connected to your Wishfin account, and we have no jurisdiction over the same.","You will receive a call from a Wish Expert ONLY if you express interest / apply for a product recommended to you by our neutral algorithm on the app. No unsolicited calls will be made to you - that’s a Wishfin promise. If you do receive a call which you feel you should not have received, please let us know at contactus@wishfin.com."]
        setUpTableView()
    }
    
    /// Set Table View
    func setUpTableView() {
        // Register Cells
        self.appRelTableView.register(UINib.init(nibName: "HelpCell", bundle: nil), forCellReuseIdentifier: "HelpCell")
        self.appRelTableView.tableFooterView = UIView()
        self.appRelTableView.estimatedRowHeight = 44.0
        self.appRelTableView.rowHeight = UITableView.automaticDimension
    }
    
    @IBAction func backBtnClicked(_ sender: Any) {
        self.navigationController?.popViewController(animated: true)
    }

}

// MARK: UITableView Datasource
extension AppRelatedVC : UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return titleArray.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "HelpCell", for: indexPath) as! HelpCell
        cell.setupCellUI(title: titleArray[indexPath.row])
        return cell
    }
}

// MARK: UITableView Delegate
extension AppRelatedVC : UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let obj = HelpDetailVC.init(nibName: "HelpDetailVC", bundle: nil)
        obj.titleString = titleArray[indexPath.row]
        obj.detailString = detailArray[indexPath.row]
        self.navigationController?.pushViewController(obj, animated: true)
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 44
    }
}
